name: Test Suite

on:
  pull_request:
  push:
    branches: [ 1.x ]
  schedule: [ { cron: '0 8 * * *' } ]

jobs:
  tests:
    services:
      elasticsearch:
        image: elasticsearch:7.17.2
        env:
          discovery.type: single-node
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 9200:9200
      postgres:
        image: postgres:13.6-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    name: "Tests"
    uses: flow-php/actions/.github/workflows/composer-script-test.yaml@main

  static-analyze:
    name: "Static Analyze"
    uses: flow-php/actions/.github/workflows/composer-script-static-analyze.yaml@main

  mutation-tests:
    name: "Mutation Tests"
    uses: flow-php/actions/.github/workflows/composer-script-mutation.yaml@main
    secrets:
      infection_badge_api_key: ${{ secrets.INFECTION_BADGE_API_KEY }}
      stryker_dashboard_api_key: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
